"""lc_render.py — problem data -> Obsidian note, and note -> section access.

The note is the single source of truth for the whole workflow: `lc sync` reads
its code block and prose back out to build the git repo. So the section
headings here are a contract, and `SECTIONS` is the one place they are named.
"""
from __future__ import annotations

import datetime as dt
import re
from typing import Any

from lccore import (
    GEN_BEGIN,
    GEN_END,
    NOTE_TYPE,
    fmt_duration,
    parse_ts,
)

H_PROBLEM = "Problem"
H_EXAMPLES = "Examples"
H_CONSTRAINTS = "Constraints"
H_APPROACH = "My approach"
H_SOLUTION = "Solution"
H_COMPLEXITY = "Complexity"
H_EXPLANATION = "Explanation"
H_MISTAKES = "Mistakes / what to remember"
H_REVIEW = "Review"

# Sections copied verbatim into the repo README for each problem.
PUBLISHED_SECTIONS = [H_APPROACH, H_COMPLEXITY, H_EXPLANATION, H_MISTAKES]

# Written into the note as-is; `lc sync` treats an unchanged block as "empty".
PLACEHOLDER_APPROACH = "> Before you write any code: what's the brute force, and what's the insight that beats it?"
PLACEHOLDER_EXPLANATION = "> Explain the working solution in your own words, as if teaching it. This is what lands in the repo README."


def source_name(link: str) -> str:
    """Whose site is this? NeetCode hosts problems LeetCode has no twin for."""
    return "NeetCode" if "neetcode.io" in str(link).lower() else "LeetCode"


def difficulty_badge(difficulty: str) -> str:
    return {"Easy": "🟢 Easy", "Medium": "🟡 Medium", "Hard": "🔴 Hard"}.get(
        difficulty, f"⚪️ {difficulty}"
    )


def build_meta(problem: dict[str, Any], today: dt.date | None = None) -> dict[str, Any]:
    today = today or dt.date.today()
    return {
        "type": NOTE_TYPE,
        "title": problem["title"],
        "slug": problem["slug"],
        "id": problem["id"],
        "link": problem["link"],
        "difficulty": problem["difficulty"],
        "topics": list(problem.get("topics") or []),
        "status": "attempted",
        "date": today.isoformat(),
        "started_at": None,
        "ended_at": None,
        "time_spent_min": 0,
        "attempts": 1,
        "solved_without_help": None,
        "next_review": None,
        "tags": ["leetcode", problem["difficulty"].lower()],
    }


def render_body(problem: dict[str, Any]) -> str:
    """The note body. Everything above 'My approach' is regenerated by
    `lc refresh`; everything below it is yours."""
    parts: list[str] = []

    parts.append(GEN_BEGIN)
    parts.append(f"# {problem['id']}. {problem['title']}")
    meta_line = [
        f"[🔗 Open on {source_name(problem['link'])}]({problem['link']})",
        difficulty_badge(problem["difficulty"]),
    ]
    if problem.get("acceptance"):
        meta_line.append(f"{problem['acceptance']} accepted")
    if problem.get("topics"):
        meta_line.append(" · ".join(f"`{t}`" for t in problem["topics"]))
    parts.append("  \n".join(meta_line))

    parts.append(f"## {H_PROBLEM}")
    parts.append(problem.get("description") or "_No description available._")

    if problem.get("examples"):
        parts.append(f"## {H_EXAMPLES}")
        parts.append(problem["examples"])

    if problem.get("constraints"):
        parts.append(f"## {H_CONSTRAINTS}")
        parts.append(problem["constraints"])

    if problem.get("follow_up"):
        parts.append("## Follow-up")
        parts.append(problem["follow_up"])

    if problem.get("hints"):
        from lc_fetch import html_to_markdown

        hints = "\n".join(
            f"{i}. {html_to_markdown(h)}" for i, h in enumerate(problem["hints"], 1)
        )
        parts.append(f"## Hints\n\n> [!tip]- Spoilers — open only if you're stuck\n> \n"
                     + "\n".join(f"> {line}" for line in hints.split("\n")))
    parts.append(GEN_END)

    parts.append(f"## {H_APPROACH}")
    parts.append(PLACEHOLDER_APPROACH)

    parts.append(f"## {H_SOLUTION}")
    parts.append(f"```python\n{problem['starter']}\n```")

    parts.append(f"## {H_COMPLEXITY}")
    parts.append("**Time:** `O()`  \n**Space:** `O()`")

    parts.append(f"## {H_EXPLANATION}")
    parts.append(PLACEHOLDER_EXPLANATION)

    parts.append(f"## {H_MISTAKES}")
    parts.append("- ")

    parts.append(f"## {H_REVIEW}")
    parts.append(
        "- [ ] I can explain the optimal solution without looking\n"
        "- [ ] I understand the time and space complexity\n"
        "- [ ] I understand why my first approach fell short\n"
        "- [ ] I could code this from scratch in 15 minutes"
    )

    return "\n\n".join(parts)


# --------------------------------------------------------------------------- reading back


def section(body: str, heading: str) -> str:
    """Text under '## <heading>', up to the next '## '. Empty if absent."""
    pattern = re.compile(rf"^##[ \t]+{re.escape(heading)}[ \t]*$", re.M)
    m = pattern.search(body)
    if not m:
        return ""
    rest = body[m.end():]
    nxt = re.search(r"^##\s+", rest, re.M)
    text = (rest[: nxt.start()] if nxt else rest).strip()
    return "" if text == GEN_END else text.replace(GEN_END, "").strip()


def replace_section(body: str, heading: str, new_text: str) -> str:
    pattern = re.compile(rf"^##[ \t]+{re.escape(heading)}[ \t]*$", re.M)
    m = pattern.search(body)
    if not m:
        return body.rstrip() + f"\n\n## {heading}\n\n{new_text.strip()}\n"
    rest = body[m.end():]
    nxt = re.search(r"^##\s+", rest, re.M)
    tail = rest[nxt.start():] if nxt else ""
    joiner = "\n\n" if tail else "\n"
    return body[: m.end()] + "\n\n" + new_text.strip() + joiner + tail


CODE_FENCE = re.compile(r"```(?:python|py)\s*\n(.*?)^```", re.S | re.M)


def extract_code(body: str) -> str:
    """The Solution section's python block (falls back to the first in the note)."""
    sol = section(body, H_SOLUTION)
    m = CODE_FENCE.search(sol) or CODE_FENCE.search(body)
    return m.group(1).rstrip() if m else ""


def replace_code(body: str, code: str) -> str:
    block = f"```python\n{code.rstrip()}\n```"
    sol = section(body, H_SOLUTION)
    if CODE_FENCE.search(sol):
        replaced = CODE_FENCE.sub(lambda _: block, sol, count=1)
    else:
        replaced = (sol + "\n\n" + block).strip()
    return replace_section(body, H_SOLUTION, re.sub(r"\n{3,}", "\n\n", replaced))


def is_placeholder_code(code: str, starter: str = "") -> bool:
    """True when the block has no real solution in it yet.

    Guards `lc sync`: a note whose code block was never filled in must not be
    allowed to wipe a solution.py the user wrote in their editor.
    """
    stripped = "\n".join(
        line for line in code.split("\n")
        if line.strip() and not line.strip().startswith("#")
    )
    if not stripped.strip():
        return True
    if starter and _normalize(code) == _normalize(starter):
        return True
    # A body that is nothing but `pass` / `...` / `TODO` is still a stub.
    bodyless = re.sub(r"^\s*(pass|\.\.\.)\s*$", "", stripped, flags=re.M)
    bodyless = re.sub(r"^\s*(class|def)\s.*$", "", bodyless, flags=re.M)
    return not bodyless.strip()


def _normalize(code: str) -> str:
    return "\n".join(l.rstrip() for l in code.strip().split("\n") if l.strip())


def is_placeholder_prose(text: str) -> bool:
    if not text.strip():
        return True
    cleaned = text.strip()
    if cleaned in (PLACEHOLDER_APPROACH, PLACEHOLDER_EXPLANATION, "-", "- "):
        return True
    # A section of nothing but empty bullets or an untouched callout.
    meaningful = [
        l for l in cleaned.split("\n")
        if l.strip() not in ("", "-", "- ", "*") and not l.strip().startswith(">")
    ]
    return not meaningful


def stats_line(meta: dict[str, Any]) -> str:
    bits = [
        f"**Status:** {str(meta.get('status', 'attempted')).capitalize()}",
        f"**Time:** {fmt_duration(meta.get('time_spent_min'))}",
        f"**Attempts:** {meta.get('attempts', 1)}",
    ]
    if meta.get("date"):
        bits.append(f"**Date:** {meta['date']}")
    if meta.get("next_review"):
        bits.append(f"**Review on:** {meta['next_review']}")
    started, ended = parse_ts(meta.get("started_at")), parse_ts(meta.get("ended_at"))
    if started and ended:
        bits.append(f"**Solved:** {started:%H:%M}–{ended:%H:%M}")
    return " · ".join(bits)


def render_note(problem: dict[str, Any], today: dt.date | None = None) -> tuple[dict[str, Any], str]:
    return build_meta(problem, today), render_body(problem)
